import "server-only";

type ServerEnv = {
  NEXT_PUBLIC_SUPABASE_URL?: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  SUPABASE_SECRET_KEY?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  STRIPE_SUCCESS_URL?: string;
  STRIPE_CANCEL_URL?: string;
  STRIPE_CHECKOUT_LIVE_MODE?: string;
  STRIPE_CHECKOUT_ALLOW_PLACEHOLDER?: string;
  STRIPE_PAYMENT_CONFIRMATION_SOURCE?: string;
  RESEND_API_KEY?: string;
  RESEND_CONTACT_TEMPLATE_ID?: string;
  RESEND_TEMPLATE_NAME?: string;
  CONTACT_OWNER_EMAIL?: string;
  CONTACT_FROM_EMAIL?: string;
  EMAIL_INTERNAL_TO?: string;
  ORDERS_OWNER_EMAIL?: string;
  ORDERS_SEND_BUYER_ACK?: string;
  ORDER_EMAIL_ROUTE_SECRET?: string;
  CHECKOUT_SITE_URL?: string;
  CAL_WEBHOOK_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
  NEXT_PUBLIC_CHECKOUT_URL?: string;
  NEXT_PUBLIC_SECURE_UPLOAD_URL?: string;
  NEXT_PUBLIC_STRATEGY_CALL_URL?: string;
  NEXT_PUBLIC_ANALYTICS_ENABLED?: string;
  NEXT_PUBLIC_CAL_DETAILFLOW_SETUP_URL?: string;
  NEXT_PUBLIC_CAL_INKBOT_PLANNING_URL?: string;
  NEXT_PUBLIC_CAL_CUSTOM_PROJECT_URL?: string;
  NEXT_PUBLIC_CAL_FREE_STRATEGY_URL?: string;
};

export const env: ServerEnv = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_SECRET_KEY: process.env.SUPABASE_SECRET_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_SUCCESS_URL: process.env.STRIPE_SUCCESS_URL,
  STRIPE_CANCEL_URL: process.env.STRIPE_CANCEL_URL,
  STRIPE_CHECKOUT_LIVE_MODE: process.env.STRIPE_CHECKOUT_LIVE_MODE,
  STRIPE_CHECKOUT_ALLOW_PLACEHOLDER: process.env.STRIPE_CHECKOUT_ALLOW_PLACEHOLDER,
  STRIPE_PAYMENT_CONFIRMATION_SOURCE: process.env.STRIPE_PAYMENT_CONFIRMATION_SOURCE,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_CONTACT_TEMPLATE_ID: process.env.RESEND_CONTACT_TEMPLATE_ID,
  RESEND_TEMPLATE_NAME: process.env.RESEND_TEMPLATE_NAME,
  CONTACT_OWNER_EMAIL: process.env.CONTACT_OWNER_EMAIL,
  CONTACT_FROM_EMAIL: process.env.CONTACT_FROM_EMAIL,
  EMAIL_INTERNAL_TO: process.env.EMAIL_INTERNAL_TO,
  ORDERS_OWNER_EMAIL: process.env.ORDERS_OWNER_EMAIL,
  ORDERS_SEND_BUYER_ACK: process.env.ORDERS_SEND_BUYER_ACK,
  ORDER_EMAIL_ROUTE_SECRET: process.env.ORDER_EMAIL_ROUTE_SECRET,
  CHECKOUT_SITE_URL: process.env.CHECKOUT_SITE_URL,
  CAL_WEBHOOK_SECRET: process.env.CAL_WEBHOOK_SECRET,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_CHECKOUT_URL: process.env.NEXT_PUBLIC_CHECKOUT_URL,
  NEXT_PUBLIC_SECURE_UPLOAD_URL: process.env.NEXT_PUBLIC_SECURE_UPLOAD_URL,
  NEXT_PUBLIC_STRATEGY_CALL_URL: process.env.NEXT_PUBLIC_STRATEGY_CALL_URL,
  NEXT_PUBLIC_ANALYTICS_ENABLED: process.env.NEXT_PUBLIC_ANALYTICS_ENABLED,
  NEXT_PUBLIC_CAL_DETAILFLOW_SETUP_URL: process.env.NEXT_PUBLIC_CAL_DETAILFLOW_SETUP_URL,
  NEXT_PUBLIC_CAL_INKBOT_PLANNING_URL: process.env.NEXT_PUBLIC_CAL_INKBOT_PLANNING_URL,
  NEXT_PUBLIC_CAL_CUSTOM_PROJECT_URL: process.env.NEXT_PUBLIC_CAL_CUSTOM_PROJECT_URL,
  NEXT_PUBLIC_CAL_FREE_STRATEGY_URL: process.env.NEXT_PUBLIC_CAL_FREE_STRATEGY_URL,
};
