type PublicEnv = {
  NEXT_PUBLIC_SITE_URL?: string;
  NEXT_PUBLIC_CHECKOUT_URL?: string;
  NEXT_PUBLIC_SECURE_UPLOAD_URL?: string;
  NEXT_PUBLIC_STRATEGY_CALL_URL?: string;
  NEXT_PUBLIC_ANALYTICS_ENABLED?: string;
  NEXT_PUBLIC_CAL_DETAILFLOW_SETUP_URL?: string;
  NEXT_PUBLIC_CAL_INKBOT_PLANNING_URL?: string;
  NEXT_PUBLIC_CAL_CUSTOM_PROJECT_URL?: string;
  NEXT_PUBLIC_CAL_FREE_STRATEGY_URL?: string;
};

export const publicEnv: PublicEnv = {
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_CHECKOUT_URL: process.env.NEXT_PUBLIC_CHECKOUT_URL,
  NEXT_PUBLIC_SECURE_UPLOAD_URL: process.env.NEXT_PUBLIC_SECURE_UPLOAD_URL,
  NEXT_PUBLIC_STRATEGY_CALL_URL: process.env.NEXT_PUBLIC_STRATEGY_CALL_URL,
  NEXT_PUBLIC_ANALYTICS_ENABLED: process.env.NEXT_PUBLIC_ANALYTICS_ENABLED,
  NEXT_PUBLIC_CAL_DETAILFLOW_SETUP_URL: process.env.NEXT_PUBLIC_CAL_DETAILFLOW_SETUP_URL,
  NEXT_PUBLIC_CAL_INKBOT_PLANNING_URL: process.env.NEXT_PUBLIC_CAL_INKBOT_PLANNING_URL,
  NEXT_PUBLIC_CAL_CUSTOM_PROJECT_URL: process.env.NEXT_PUBLIC_CAL_CUSTOM_PROJECT_URL,
  NEXT_PUBLIC_CAL_FREE_STRATEGY_URL: process.env.NEXT_PUBLIC_CAL_FREE_STRATEGY_URL,
};
